name: Continuous Delivery

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release and Upload Python Distributions
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. Install build tools
      - name: Install build tools
        run: |
          python -m pip install --upgrade build setuptools wheel

      # 4. Build the package
      - name: Build Python package
        run: |
          rm -rf dist
          python -m build --outdir dist

      # 5. Create and publish GitHub release with distributions
      - name: Upload Python distributions
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: false         # Create as published (this triggers release.published)
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

