name: Continuous Delivery

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release and Upload Python Distributions
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. Install build tools
      - name: Install build tools
        run: |
          python -m pip install --upgrade build setuptools wheel

      # 4. Build the package
      - name: Build Python package
        run: |
          rm -rf dist
          python -m build --outdir dist

      # 5. Upload distributions to the release
      - name: Upload Python distributions
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6. Publish the release
      - name: Publish Release
        run: |
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }} \
            -d '{"draft": false}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
