name: Publish to PyPI.org

on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo with full history
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install build tools
      - name: Install build tools
        run: |
          python3 -m pip install --upgrade build setuptools wheel twine

      # 4. Build the package into dist/
      - name: Build Python package
        run: |
          rm -rf dist
          python3 -m build --outdir dist

      # 5. Optional: check the built distributions
      - name: Check distributions
        run: |
          python3 -m twine check dist/*

      # 6. Publish to PyPI
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
